/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EMS;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class AddEmployee extends javax.swing.JFrame {

    int count;
    private String id;
    private String name;
    private String surname;
    private String gender;
    private String email;
    private String contact;
    private String designation;
    private String department;
    private String status;
    private String datehired;
    private String dob;
    private String salary;
    private String jobtitle;
    private String address1;
    private String address2;
    private String houseno;
    private String postcode;
    private String imageIcon;
    FileInputStream fin;

    private String getCurrentDateTime() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        String dateTime = (month + 1) + "/" + day + "/" + year + " , " + hour + ":" + minute + ":" + second;
        return dateTime;
    }

    public AddEmployee() {
        try {
            this.count = idCount() + 1;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jftid = new javax.swing.JFormattedTextField();
        jtfname = new javax.swing.JTextField();
        jtfsurname = new javax.swing.JTextField();
        jcbdepartment = new javax.swing.JComboBox<>();
        jcbdesignation = new javax.swing.JComboBox<>();
        jcbstatus = new javax.swing.JComboBox<>();
        jtfsalary = new javax.swing.JTextField();
        jtftitle = new javax.swing.JTextField();
        jtfhouseno = new javax.swing.JTextField();
        jtfadd2 = new javax.swing.JTextField();
        jtfadd1 = new javax.swing.JTextField();
        jtfemail = new javax.swing.JTextField();
        jftcontact = new javax.swing.JFormattedTextField();
        jftpostcode = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtadd = new javax.swing.JButton();
        jbtcancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jrbgenfemale = new javax.swing.JRadioButton();
        jrbgenmale = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        buttonGroup1.add(jrbgenmale);
        buttonGroup1.add(jrbgenfemale);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel3.setLabelFor(jftid);
        jLabel3.setText("Employee id:-");
        jLabel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel3FocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel4.setLabelFor(jtfname);
        jLabel4.setText("Name:-");

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel5.setLabelFor(jtfsurname);
        jLabel5.setText("Surname:-");

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel6.setText("Date of Birth:-");

        jLabel7.setLabelFor(jrbgenmale);
        jLabel7.setText("Gender:-");

        jLabel9.setLabelFor(jtfemail);
        jLabel9.setText("Email:-");

        jLabel10.setLabelFor(jftcontact);
        jLabel10.setText("Contact:-");

        jLabel11.setLabelFor(jtfadd1);
        jLabel11.setText("Address line 1:-");

        jLabel12.setLabelFor(jtfadd2);
        jLabel12.setText("Address line 2:-");

        jLabel13.setLabelFor(jtfhouseno);
        jLabel13.setText("House no:-");

        jLabel14.setLabelFor(jftpostcode);
        jLabel14.setText("Post code:-");

        jLabel8.setLabelFor(jcbdepartment);
        jLabel8.setText("Department:-");

        jLabel15.setLabelFor(jcbdesignation);
        jLabel15.setText("Designation:-");

        jLabel16.setLabelFor(jcbstatus);
        jLabel16.setText("Status:-");

        jLabel17.setText("Date hired:-");

        jLabel18.setLabelFor(jtfsalary);
        jLabel18.setText("Basic salary:-");

        jLabel19.setLabelFor(jtftitle);
        jLabel19.setText("Job title:-");

        jLabel20.setBackground(new java.awt.Color(0, 153, 153));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("<html>click<br>to add<br>image");
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jftid.setText(Integer.toString(count));
        jftid.setEnabled(false);
        jftid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftidActionPerformed(evt);
            }
        });
        jftid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftidKeyPressed(evt);
            }
        });

        jtfname.setToolTipText("hi");
        jtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfnameKeyPressed(evt);
            }
        });

        jtfsurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfsurnameKeyPressed(evt);
            }
        });

        jcbdepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "ME", "CS", "TT", "TC", "EC" }));
        jcbdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdepartmentActionPerformed(evt);
            }
        });
        jcbdepartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbdepartmentKeyPressed(evt);
            }
        });

        jcbdesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEO", "CTO", "CMO", "SENIOR MANAGER", "MANAGER", "DEVELOPER", "DESIGNER", "HELPER" }));
        jcbdesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbdesignationKeyPressed(evt);
            }
        });

        jcbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARRIED", "UNMARRIED", "DEVORSED" }));
        jcbstatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbstatusKeyPressed(evt);
            }
        });

        jtfsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfsalaryActionPerformed(evt);
            }
        });
        jtfsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfsalaryKeyPressed(evt);
            }
        });

        jtftitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtftitleKeyPressed(evt);
            }
        });

        jtfhouseno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfhousenoKeyPressed(evt);
            }
        });

        jtfadd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfadd2KeyPressed(evt);
            }
        });

        jtfadd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfadd1KeyPressed(evt);
            }
        });

        jtfemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfemailKeyPressed(evt);
            }
        });

        jftcontact.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));
        jftcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftcontactActionPerformed(evt);
            }
        });
        jftcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftcontactKeyPressed(evt);
            }
        });

        jftpostcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftpostcodeKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jbtadd.setText("Add record");
        jbtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddActionPerformed(evt);
            }
        });

        jbtcancel.setText("Cancel");
        jbtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtadd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jbtcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtcancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtadd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        jrbgenfemale.setText("Female");
        jrbgenfemale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbgenfemaleKeyPressed(evt);
            }
        });

        jrbgenmale.setSelected(true);
        jrbgenmale.setText("Male");
        jrbgenmale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbgenmaleKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbgenmale)
                .addGap(26, 26, 26)
                .addComponent(jrbgenfemale)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbgenmale)
                    .addComponent(jrbgenfemale))
                .addContainerGap())
        );

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jDateChooser2.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfhouseno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfadd2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftcontact, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfemail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jftid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfsurname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfadd1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jftpostcode))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jcbdepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcbstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcbdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfsalary, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jtftitle))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jftid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jcbdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jcbdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jtfsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jcbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel17))
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel18)
                            .addComponent(jtfsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtftitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jftcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jtfadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfhouseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jftpostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(getCurrentDateTime());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Employee details");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3FocusGained

    private void jtfsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfsalaryActionPerformed

    private void jftidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftidActionPerformed

    private void jftidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jftid.transferFocus();
        }
    }//GEN-LAST:event_jftidKeyPressed

    private void jtfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfname.transferFocus();
        }
    }//GEN-LAST:event_jtfnameKeyPressed

    private void jtfsurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfsurnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfsurname.transferFocus();
        }
    }//GEN-LAST:event_jtfsurnameKeyPressed

    private void jrbgenmaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbgenmaleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbgenmale.transferFocus();
        }
    }//GEN-LAST:event_jrbgenmaleKeyPressed

    private void jtfemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfemailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfemail.transferFocus();
        }
    }//GEN-LAST:event_jtfemailKeyPressed

    private void jftcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftcontactKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jftcontact.transferFocus();
        }
    }//GEN-LAST:event_jftcontactKeyPressed

    private void jtfadd1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfadd1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfadd1.transferFocus();
        }
    }//GEN-LAST:event_jtfadd1KeyPressed

    private void jtfadd2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfadd2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfadd2.transferFocus();
        }
    }//GEN-LAST:event_jtfadd2KeyPressed

    private void jtfhousenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfhousenoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfhouseno.transferFocus();
        }
    }//GEN-LAST:event_jtfhousenoKeyPressed

    private void jftpostcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftpostcodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jftpostcode.transferFocus();
            jbtadd.doClick();
        }
    }//GEN-LAST:event_jftpostcodeKeyPressed

    private void jcbdepartmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbdepartmentKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcbdepartment.transferFocus();
        }
    }//GEN-LAST:event_jcbdepartmentKeyPressed

    private void jcbdesignationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbdesignationKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcbdesignation.transferFocus();
        }
    }//GEN-LAST:event_jcbdesignationKeyPressed

    private void jcbstatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbstatusKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcbstatus.transferFocus();
        }
    }//GEN-LAST:event_jcbstatusKeyPressed

    private void jtfsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfsalaryKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfsalary.transferFocus();
        }
    }//GEN-LAST:event_jtfsalaryKeyPressed

    private void jtftitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtftitleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtftitle.transferFocus();
        }
    }//GEN-LAST:event_jtftitleKeyPressed

    private void jrbgenfemaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbgenfemaleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbgenfemale.transferFocus();
        }
    }//GEN-LAST:event_jrbgenfemaleKeyPressed
    int idCount() throws ClassNotFoundException, SQLException {
        Class.forName("com.mysql.cj.jdbc.Driver");

        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/shubham", "root", "")) {

            PreparedStatement countQuery = connection.prepareStatement("SELECT COUNT(*) FROM employee");
            ResultSet resultSet = countQuery.executeQuery();

            int number = 0;
            if (resultSet.next()) {
                number = resultSet.getInt(1);
            }

            return number;
        }
    }
    private void jbtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtaddActionPerformed

        id = jftid.getText();
        name = jtfname.getText();
        surname = jtfsurname.getText();

        if (jrbgenmale.isSelected() == true) {
            gender = "male";

        }
        if (jrbgenfemale.isSelected() == true) {
            gender = "female";
        }
        System.out.println(gender);
        email = jtfemail.getText();
        contact = jftcontact.getText();
        designation = jcbdesignation.getSelectedItem().toString();
        department = jcbdepartment.getSelectedItem().toString();
        status = jcbstatus.getSelectedItem().toString();
        SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        String date = fmt.format(jDateChooser1.getDate()); //jdatechooser
        datehired = fmt.format(jDateChooser1.getDate());
        dob = fmt.format(jDateChooser2.getDate());
        System.out.println(datehired);
        System.out.println(dob);
        salary = jtfsalary.getText();
        jobtitle = jtftitle.getText();
        address1 = jtfadd1.getText();
        address2 = jtfadd2.getText();
        houseno = jtfhouseno.getText();
        postcode = jftpostcode.getText();
        if (id.isEmpty() || name.isEmpty() || surname.isEmpty() || email.isEmpty()
                || contact.isEmpty() || designation.isEmpty() || department.isEmpty() || status.isEmpty()
                || datehired.isEmpty() || dob.isEmpty() || salary.isEmpty() || jobtitle.isEmpty()
                || address1.isEmpty() || houseno.isEmpty() || postcode.isEmpty()) {

            // Show an option or message to the user
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Incomplete Form", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                System.out.println("Driver loaded");

                // Connect to a database
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/shubham", "root", "");
                System.out.println("Database connected");

                PreparedStatement stmt = connection.prepareStatement("insert into employee values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                stmt.setString(1, id);
                stmt.setString(2, name);
                stmt.setString(3, surname);
                stmt.setString(4, dob);
                stmt.setString(5, gender);
                stmt.setString(6, department);
                stmt.setString(7, designation);
                stmt.setString(8, status);
                stmt.setString(9, datehired);
                stmt.setString(10, salary);
                stmt.setString(11, jobtitle);
                stmt.setString(12, email);
                stmt.setString(13, contact);
                stmt.setString(14, address1);
                stmt.setString(15, address2);
                stmt.setString(16, houseno);
                stmt.setString(17, postcode);
                stmt.setBinaryStream(18, fin, fin.available());
                int norows = stmt.executeUpdate();
                System.out.println("No of rows affected=" + norows);
                if (norows != 0) {
                    String s[] = null;
                    LoginPage.main(s);
                    dispose();
                }

                connection.close();
            } catch (ClassNotFoundException e) {
                System.err.println("Error loading the database driver: " + e.getMessage());
            } catch (SQLException e) {
                System.err.println("SQL Error: " + e.getMessage());
                e.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtaddActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jftcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftcontactActionPerformed

    private void jcbdepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbdepartmentActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        jLabel20.setText(""); // Clear any existing text in the label

        JFileChooser jfc = new JFileChooser();
        int result = jfc.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();

            // Check if the selected file is an image (you may need to add more file type checks)
            if (selectedFile.isFile() && (selectedFile.getName().toLowerCase().endsWith(".jpg")
                    || selectedFile.getName().toLowerCase().endsWith(".jpeg")
                    || selectedFile.getName().toLowerCase().endsWith(".png")
                    || selectedFile.getName().toLowerCase().endsWith(".gif"))) {

                String filename = selectedFile.getAbsolutePath();
                System.out.println(filename);
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jLabel20.getWidth(), jLabel20.getHeight(), Image.SCALE_DEFAULT));
                jLabel20.setIcon(imageIcon);
                try {
                   fin = new FileInputStream(selectedFile.getAbsoluteFile());
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                // Handle the case where the selected file is not an image
                jLabel20.setText("Selected file is not an image.");
            }
        }

    }//GEN-LAST:event_jLabel20MouseClicked

    private void jbtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelActionPerformed
        String s[] = null;
        form.main(s);
        dispose();
    }//GEN-LAST:event_jbtcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtadd;
    private javax.swing.JButton jbtcancel;
    private javax.swing.JComboBox<String> jcbdepartment;
    private javax.swing.JComboBox<String> jcbdesignation;
    private javax.swing.JComboBox<String> jcbstatus;
    private javax.swing.JFormattedTextField jftcontact;
    private javax.swing.JFormattedTextField jftid;
    private javax.swing.JFormattedTextField jftpostcode;
    private javax.swing.JRadioButton jrbgenfemale;
    private javax.swing.JRadioButton jrbgenmale;
    private javax.swing.JTextField jtfadd1;
    private javax.swing.JTextField jtfadd2;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JTextField jtfhouseno;
    private javax.swing.JTextField jtfname;
    private javax.swing.JTextField jtfsalary;
    private javax.swing.JTextField jtfsurname;
    private javax.swing.JTextField jtftitle;
    // End of variables declaration//GEN-END:variables

}
