package EMS;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author mlvtec-01
 */
public class RegistrationPage extends javax.swing.JFrame {

    String name;
    String email;
    String username;
    String password;
    String usertype;
    public RegistrationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnwlcom = new javax.swing.JPanel();
        jlbwelcome = new javax.swing.JLabel();
        jpnlogin = new javax.swing.JPanel();
        jtbusername = new javax.swing.JTextField();
        jbtregister = new javax.swing.JButton();
        jlbusername = new javax.swing.JLabel();
        jlbpassword = new javax.swing.JLabel();
        jlbusertap = new javax.swing.JLabel();
        jtbpassword = new javax.swing.JPasswordField();
        jtfname = new javax.swing.JTextField();
        jtbemail = new javax.swing.JTextField();
        jlbemail = new javax.swing.JLabel();
        jcbusertype = new javax.swing.JComboBox<>();
        jlbusertype = new javax.swing.JLabel();
        jlbname = new javax.swing.JLabel();
        jlbwelicon = new javax.swing.JLabel();
        jlbdevname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 0));
        setResizable(false);

        jpnwlcom.setBackground(new java.awt.Color(0, 0, 153));

        jlbwelcome.setFont(new java.awt.Font("Lucida Grande", 1, 68)); // NOI18N
        jlbwelcome.setForeground(new java.awt.Color(255, 255, 255));
        jlbwelcome.setText("Welcome");

        jpnlogin.setBackground(new java.awt.Color(255, 255, 0));
        jpnlogin.setBorder(new javax.swing.border.MatteBorder(null));

        jtbusername.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jtbusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbusernameKeyPressed(evt);
            }
        });

        jbtregister.setBackground(new java.awt.Color(204, 204, 0));
        jbtregister.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbtregister.setText("Register");
        jbtregister.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtregister.setOpaque(true);
        jbtregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtregisterActionPerformed(evt);
            }
        });
        jbtregister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtregisterKeyPressed(evt);
            }
        });

        jlbusername.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlbusername.setText("Username");

        jlbpassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlbpassword.setText("Password");

        jlbusertap.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlbusertap.setText("Login");
        jlbusertap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbusertapMouseClicked(evt);
            }
        });

        jtbpassword.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jtbpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbpasswordKeyPressed(evt);
            }
        });

        jtfname.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnameActionPerformed(evt);
            }
        });
        jtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfnameKeyPressed(evt);
            }
        });

        jtbemail.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jtbemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbemailActionPerformed(evt);
            }
        });
        jtbemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbemailKeyPressed(evt);
            }
        });

        jlbemail.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlbemail.setText("Email");

        jcbusertype.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jcbusertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "user" }));
        jcbusertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbusertypeActionPerformed(evt);
            }
        });
        jcbusertype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbusertypeKeyPressed(evt);
            }
        });

        jlbusertype.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlbusertype.setText("User type");

        jlbname.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jlbname.setText("Name");

        javax.swing.GroupLayout jpnloginLayout = new javax.swing.GroupLayout(jpnlogin);
        jpnlogin.setLayout(jpnloginLayout);
        jpnloginLayout.setHorizontalGroup(
            jpnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnloginLayout.createSequentialGroup()
                .addGroup(jpnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnloginLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jlbemail))
                    .addGroup(jpnloginLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jpnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfname)
                            .addComponent(jtbemail)
                            .addComponent(jtbusername)
                            .addComponent(jtbpassword)
                            .addComponent(jcbusertype, 0, 292, Short.MAX_VALUE)))
                    .addGroup(jpnloginLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jlbusername))
                    .addGroup(jpnloginLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jlbusertype))
                    .addGroup(jpnloginLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jlbpassword))
                    .addGroup(jpnloginLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jlbname)))
                .addGap(146, 158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnloginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnloginLayout.createSequentialGroup()
                        .addComponent(jlbusertap, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnloginLayout.createSequentialGroup()
                        .addComponent(jbtregister, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))))
        );
        jpnloginLayout.setVerticalGroup(
            jpnloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnloginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlbname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jlbemail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jlbusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jlbpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbusertype)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbusertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jbtregister, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbusertap, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        jlbdevname.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlbdevname.setForeground(new java.awt.Color(255, 255, 255));
        jlbdevname.setText("@Ashu sharma");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMS/EMS.png"))); // NOI18N

        javax.swing.GroupLayout jpnwlcomLayout = new javax.swing.GroupLayout(jpnwlcom);
        jpnwlcom.setLayout(jpnwlcomLayout);
        jpnwlcomLayout.setHorizontalGroup(
            jpnwlcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnwlcomLayout.createSequentialGroup()
                .addGroup(jpnwlcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnwlcomLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jlbwelicon, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnwlcomLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnwlcomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnwlcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnwlcomLayout.createSequentialGroup()
                                .addComponent(jlbdevname)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnwlcomLayout.createSequentialGroup()
                                .addComponent(jlbwelcome)
                                .addGap(49, 49, 49)))))
                .addComponent(jpnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnwlcomLayout.setVerticalGroup(
            jpnwlcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnwlcomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbwelicon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jlbdevname)
                .addContainerGap())
            .addComponent(jpnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 677, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnwlcom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnwlcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbusernameKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtbusername.transferFocus();
        }
    }//GEN-LAST:event_jtbusernameKeyPressed

    private void jtbemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbemailActionPerformed

    private void jtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnameActionPerformed

    private void jcbusertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbusertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbusertypeActionPerformed

    private void jtfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfname.transferFocus();
        }
    }//GEN-LAST:event_jtfnameKeyPressed

    private void jtbemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbemailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtbemail.transferFocus();
        }
    }//GEN-LAST:event_jtbemailKeyPressed

    private void jtbpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbpasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtbpassword.transferFocus();
        }
    }//GEN-LAST:event_jtbpasswordKeyPressed

    private void jcbusertypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbusertypeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcbusertype.transferFocus();
        }
    }//GEN-LAST:event_jcbusertypeKeyPressed

    private void jbtregisterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtregisterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbtregister.doClick();
        }
    }//GEN-LAST:event_jbtregisterKeyPressed

    private void jlbusertapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbusertapMouseClicked
        String s[] = null;
        LoginPage.main(s);
        dispose();
    }//GEN-LAST:event_jlbusertapMouseClicked

    private void jbtregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtregisterActionPerformed
        name = jtfname.getText();
        email = jtbemail.getText();
        username = jtbusername.getText();
        password = jtbpassword.getText();
        usertype = jcbusertype.getSelectedItem().toString();
//        System.out.println(name +"\n"+email+"\n"+username+"\n"+password+"\n"+usertype);
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    System.out.println("Driver loaded");

    // Connect to a database
    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/shubham", "root", "");
    System.out.println("Database connected");

    PreparedStatement stmt = connection.prepareStatement("insert into info(ename,email,username,password,type) values(?,?,?,?,?)");
    stmt.setString(1, name); // 1 specifies the first parameter in the query
    stmt.setString(2, email);
    stmt.setString(3, username);
    stmt.setString(4, password);
    stmt.setString(5, usertype);
    int norows = stmt.executeUpdate();
    System.out.println("No of rows affected=" + norows);
    if(norows != 0){
        Auditdata.auditdata(username, jbtregister.getText());
        String s[] = null;
        LoginPage.main(s);
        dispose();
    }

    connection.close();
} catch (ClassNotFoundException e) {
    System.err.println("Error loading the database driver: " + e.getMessage());
} catch (SQLException e) {
    System.err.println("SQL Error: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_jbtregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtregister;
    private javax.swing.JComboBox<String> jcbusertype;
    private javax.swing.JLabel jlbdevname;
    private javax.swing.JLabel jlbemail;
    private javax.swing.JLabel jlbname;
    private javax.swing.JLabel jlbpassword;
    private javax.swing.JLabel jlbusername;
    private javax.swing.JLabel jlbusertap;
    private javax.swing.JLabel jlbusertype;
    private javax.swing.JLabel jlbwelcome;
    private javax.swing.JLabel jlbwelicon;
    private javax.swing.JPanel jpnlogin;
    private javax.swing.JPanel jpnwlcom;
    private javax.swing.JTextField jtbemail;
    private javax.swing.JPasswordField jtbpassword;
    private javax.swing.JTextField jtbusername;
    private javax.swing.JTextField jtfname;
    // End of variables declaration//GEN-END:variables
}
